#pragma once
// Auto-generated by HELPER_SCRIPTS/update_version.py — do not edit manually
#define BUILD_VERSION_MAJOR 0
#define BUILD_VERSION_MINOR 0
#define BUILD_VERSION_PATCH 22
#define BUILD_VERSION_STRING "0.0.22"
