# Explicit RD_DSP submodule source list.
# regenSource.py does NOT auto-scan submodule SOURCE trees, so keep this
# file in sync by hand whenever new RD_DSP files are added/removed.
set(RD_DSP_SOURCES
    SUBMODULES/RD_DSP/SOURCE/HELPERS/CsvLoader.cpp
    SUBMODULES/RD_DSP/SOURCE/HELPERS/CsvLoader.h
    SUBMODULES/RD_DSP/SOURCE/INTERPOLATOR/Interpolator.h
    SUBMODULES/RD_DSP/SOURCE/OSCILLATOR/Oscillator.cpp
    SUBMODULES/RD_DSP/SOURCE/OSCILLATOR/Oscillator.h
    SUBMODULES/RD_DSP/SOURCE/RD_BUFFER/BufferFiller.cpp
    SUBMODULES/RD_DSP/SOURCE/RD_BUFFER/BufferFiller.h
    SUBMODULES/RD_DSP/SOURCE/RD_BUFFER/RD_Buffer.cpp
    SUBMODULES/RD_DSP/SOURCE/RD_BUFFER/RD_Buffer.h
    SUBMODULES/RD_DSP/SOURCE/SYNTH/Synth.cpp
    SUBMODULES/RD_DSP/SOURCE/SYNTH/Synth.h
    SUBMODULES/RD_DSP/SOURCE/SYNTH/SynthVoice.cpp
    SUBMODULES/RD_DSP/SOURCE/SYNTH/SynthVoice.h
    SUBMODULES/RD_DSP/SOURCE/WAVEFORM/WaveFactory.cpp
    SUBMODULES/RD_DSP/SOURCE/WAVEFORM/WaveFactory.h
    SUBMODULES/RD_DSP/SOURCE/WAVEFORM/Waveform.cpp
    SUBMODULES/RD_DSP/SOURCE/WAVEFORM/Waveform.h
    SUBMODULES/RD_DSP/SOURCE/WAVEFORM/Wavetable.cpp
    SUBMODULES/RD_DSP/SOURCE/WAVEFORM/Wavetable.h
)
