set(SOURCES
    SOURCE/AudioFileHelpers.h
    SOURCE/BlockAccumulator.cpp
    SOURCE/BlockAccumulator.h
    SOURCE/BufferFiller.h
    SOURCE/BufferHelper.h
    SOURCE/BufferMath.h
    SOURCE/BufferRange.h
    SOURCE/BufferWriter.h
    SOURCE/CircularBuffer.cpp
    SOURCE/CircularBuffer.h
    SOURCE/DATA_LOGGER/DataLogger.cpp
    SOURCE/DATA_LOGGER/DataLogger.h
    SOURCE/EDITORS/GainEditor.cpp
    SOURCE/EDITORS/GainEditor.h
    SOURCE/EDITORS/GrainShifterEditor.cpp
    SOURCE/EDITORS/GrainShifterEditor.h
    SOURCE/EDITORS/RD_ProcessorSwapperEditor.cpp
    SOURCE/EDITORS/RD_ProcessorSwapperEditor.h
    SOURCE/FX/Fade.cpp
    SOURCE/FX/Fade.h
    SOURCE/Interpolator.h
    SOURCE/MarkWriter.cpp
    SOURCE/MarkWriter.h
    SOURCE/PITCH/FFT_PitchDetector.cpp
    SOURCE/PITCH/FFT_PitchDetector.h
    SOURCE/PITCH/PitchManager.cpp
    SOURCE/PITCH/PitchManager.h
    SOURCE/PITCH/PitchMark.h
    SOURCE/PITCH/PitchMarker.cpp
    SOURCE/PITCH/PitchMarker.h
    SOURCE/PITCH/SynthMark.cpp
    SOURCE/PITCH/SynthMark.h
    SOURCE/PITCH/SynthMarker.cpp
    SOURCE/PITCH/SynthMarker.h
    SOURCE/PITCH/YIN_PitchDetector.cpp
    SOURCE/PITCH/YIN_PitchDetector.h
    SOURCE/PROCESSORS/BASE/RD_Processor.cpp
    SOURCE/PROCESSORS/BASE/RD_Processor.h
    SOURCE/PROCESSORS/GAIN/GainProcessor.cpp
    SOURCE/PROCESSORS/GAIN/GainProcessor.h
    SOURCE/PROCESSORS/GRAIN/Grain.h
    SOURCE/PROCESSORS/GRAIN/GrainShifterProcessor.cpp
    SOURCE/PROCESSORS/GRAIN/GrainShifterProcessor.h
    SOURCE/PROCESSORS/GRAIN/Granulator.cpp
    SOURCE/PROCESSORS/GRAIN/Granulator.h
    SOURCE/PROCESSORS/RD_ProcessorSwapper.cpp
    SOURCE/PROCESSORS/RD_ProcessorSwapper.h
    SOURCE/PROCESSORS/SANNAWAG/GrainExport.h
    SOURCE/PROCESSORS/SANNAWAG/Sannawag_TDPSOLA_Processor.cpp
    SOURCE/PROCESSORS/SANNAWAG/Sannawag_TDPSOLA_Processor.h
    SOURCE/PROCESSORS/SANNAWAG/TD_PSOLA.cpp
    SOURCE/PROCESSORS/SANNAWAG/TD_PSOLA.h
    SOURCE/RelativeFilePath.h
    SOURCE/Util/DebugLog.h
    SOURCE/Util/DebugLogger.cpp
    SOURCE/Util/DebugLogger.h
    SOURCE/Util/Juce_Header.h
    SOURCE/Util/Version.h
    SOURCE/Window.cpp
    SOURCE/Window.h
)