set(SOURCES
    SOURCE/AudioFileHelpers.h
    SOURCE/BlockAccumulator.cpp
    SOURCE/BlockAccumulator.h
    SOURCE/BufferFiller.h
    SOURCE/BufferHelper.h
    SOURCE/BufferMath.h
    SOURCE/BufferRange.h
    SOURCE/BufferWriter.h
    SOURCE/CircularBuffer.cpp
    SOURCE/CircularBuffer.h
    SOURCE/EDITORS/RD_PluginEditor.cpp
    SOURCE/EDITORS/RD_PluginEditor.h
    SOURCE/EDITORS/TDPSOLA_Editor.cpp
    SOURCE/EDITORS/TDPSOLA_Editor.h
    SOURCE/Interpolator.h
    SOURCE/MarkWriter.cpp
    SOURCE/MarkWriter.h
    SOURCE/PITCH/PitchDetector.cpp
    SOURCE/PITCH/PitchDetector.h
    SOURCE/PITCH/PitchManager.cpp
    SOURCE/PITCH/PitchManager.h
    SOURCE/PITCH/PitchMark.h
    SOURCE/PITCH/PitchMarker.cpp
    SOURCE/PITCH/PitchMarker.h
    SOURCE/PITCH/SynthMark.cpp
    SOURCE/PITCH/SynthMark.h
    SOURCE/PITCH/SynthMarker.cpp
    SOURCE/PITCH/SynthMarker.h
    SOURCE/PITCH/TD_PitchDetector.cpp
    SOURCE/PITCH/TD_PitchDetector.h
    SOURCE/PROCESSORS/GAIN/GainProcessor.cpp
    SOURCE/PROCESSORS/GAIN/GainProcessor.h
    SOURCE/PROCESSORS/GRAIN/Grain.cpp
    SOURCE/PROCESSORS/GRAIN/Grain.h
    SOURCE/PROCESSORS/GRAIN/Granulator.cpp
    SOURCE/PROCESSORS/GRAIN/Granulator.h
    SOURCE/PROCESSORS/GRAIN/GranulatorProcessor.cpp
    SOURCE/PROCESSORS/GRAIN/GranulatorProcessor.h
    SOURCE/PROCESSORS/GRAIN/PitchMarkBuffer.h
    SOURCE/PROCESSORS/GRAIN/PitchMarkHistory.h
    SOURCE/PROCESSORS/RD_PluginProcessor.cpp
    SOURCE/PROCESSORS/RD_PluginProcessor.h
    SOURCE/PROCESSORS/TDPSOLA/TDPSOLA_Editor.cpp
    SOURCE/PROCESSORS/TDPSOLA/TDPSOLA_Editor.h
    SOURCE/PROCESSORS/TDPSOLA/TDPSOLA_Processor.cpp
    SOURCE/PROCESSORS/TDPSOLA/TDPSOLA_Processor.h
    SOURCE/PROCESSORS/TDPSOLA/TD_Grain.h
    SOURCE/PROCESSORS/TDPSOLA/TD_Granulator.cpp
    SOURCE/PROCESSORS/TDPSOLA/TD_Granulator.h
    SOURCE/RelativeFilePath.h
    SOURCE/Util/DebugLog.h
    SOURCE/Util/DebugLogger.cpp
    SOURCE/Util/DebugLogger.h
    SOURCE/Util/Juce_Header.h
    SOURCE/Util/Version.h
    SOURCE/Window.cpp
    SOURCE/Window.h
)