set(TEST_SOURCES
    TESTS/BUFFER_FILLER/test_BufferFiller.cpp
    TESTS/BUFFER_FILLER/test_BufferFiller_WavFile.cpp
    TESTS/DATA_LOGGER/test_DataLogger.cpp
    TESTS/GRANULATOR/test_Grain.cpp
    TESTS/GRANULATOR/test_Granulator.cpp
    TESTS/GRANULATOR/test_Granulator_DataLogger.cpp
    TESTS/PITCH_MANAGER/test_FFT_PitchDetector.cpp
    TESTS/PITCH_MANAGER/test_PitchDetection_Arpeggios.cpp
    TESTS/PITCH_MANAGER/test_PitchDetection_Somewhere.cpp
    TESTS/PITCH_MANAGER/test_PitchManager.cpp
    TESTS/PITCH_MANAGER/test_PitchManager_DataLogger.cpp
    TESTS/PITCH_MANAGER/test_PitchMarker.cpp
    TESTS/PITCH_MANAGER/test_SynthMark.cpp
    TESTS/PITCH_MANAGER/test_SynthMarker.cpp
    TESTS/PITCH_MANAGER/test_YIN_PitchDetector.cpp
    TESTS/PROCESSORS/GAIN_PROCESSOR/test_GainProcessor.cpp
    TESTS/PROCESSORS/GAIN_PROCESSOR/test_GainProcessor_DataLogger.cpp
    TESTS/PROCESSORS/GRAIN_SHIFTER_PROCESSOR/test_GrainShifterProcessor.cpp
    TESTS/PROCESSORS/GRAIN_SHIFTER_PROCESSOR/test_GrainShifterProcessor_DataLogger.cpp
    TESTS/PROCESSORS/GRAIN_SHIFTER_PROCESSOR/test_GrainShifter_Female_Scale.cpp
    TESTS/PROCESSORS/OSCILLATOR_PROCESSOR/test_OscillatorProcessor.cpp
    TESTS/PROCESSORS/RD_PROCESSOR/test_RD_Processor.cpp
    TESTS/PROCESSORS/RD_PROCESSOR/test_RD_Processor_DataLogger.cpp
    TESTS/PROCESSORS/RD_PROCESSOR_SWAPPER/test_RDProcessorSwapper.cpp
    TESTS/PROCESSORS/RD_PROCESSOR_SWAPPER/test_RDProcessorSwapperEditor.cpp
    TESTS/PROCESSORS/RD_PROCESSOR_SWAPPER/test_RDProcessorSwapper_DataLogger.cpp
    TESTS/PROCESSORS/SYNTH_PROCESSOR/test_SynthProcessor.cpp
    TESTS/TEST_UTILS/BufferGenerator.h
    TESTS/TEST_UTILS/TestUtils.cpp
    TESTS/TEST_UTILS/TestUtils.h
    TESTS/test_AudioFileHelpers.cpp
    TESTS/test_AudioFileProcessor.cpp
    TESTS/test_BlockAccumulator.cpp
    TESTS/test_BufferHelper.cpp
    TESTS/test_BufferMath.cpp
    TESTS/test_BufferRange.cpp
    TESTS/test_BufferWriter.cpp
    TESTS/test_CircularBuffer.cpp
    TESTS/test_Fade.cpp
    TESTS/test_ParamHelper.cpp
    TESTS/test_RelativeFilePath.cpp
    TESTS/test_Windowing.cpp
    TESTS/test_main.cpp
    TESTS/tests_Interpolator.cpp
)